# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40a88b14ec64a501c727749c35106105237f2bd0907c56a363a260b43e61d26bfa698a8429b77d9abe61b722bfebc4dca6acb5942d902f646f54d4ac530a3f91

test:
  secret_key_base: 6a0244a3601282a8070d2c96f401c20a2089d79db2e3b1b4cd0f266eec9e5e1281abf465fdc67bae5ebeb098bb585d4617fae4beea7c616f2ad23b5a3ffbf182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
